package com.secqure.secqureauth

const val SECQURE_WEBSDK_URL = "https://api.secuuth.io/auth/getLoginWebview/"
const val CALLBACK_ACTIVITY_NAME = "CALLBACK_ACTIVITY_NAME"
const val SHARED_PREF_FILENAME = "com.secqure.androidsdk.SECQURE_SHARED_PREF"
const val SHARED_PREF_DEVICE_ID = "SECQURE_SHARED_PREF_FILE"
const val LOGIN_SUCCESS_MESSAGE = "LOGIN_SUCCESS_MESSAGE"
const val SECQURE_API_URL = "https://api.secuuth.io"
const val SECQURE_TOKENS = "tokens"
const val SECQURE_USER = "user"
const val SECQURE_USER_IDENTITY = "userIdentity"
const val SECQURE_PUB_KEY = "pubKey"
const val SECQURE_PUBLIC_KEY = "publicKey"
const val SECQURE_SYSTEM_ID = "systemId"
const val SECQURE_USER_SUB_ID = "userSubId"
const val SECQURE_REFRESH_TOKEN = "refreshToken"
const val SECQURE_RENEW_REFRESH_TOKEN = "renewRefreshToken"
